### ISSUE TITLE
Doesn't load when there are multiple maps

### ISSUE THREAD

**Issue by levipadre** [ArnoldV/Our.Umbraco.GMaps#13]
Hi,

Thanks for the package, it's really helpful.
When I'm using the map in nested content, it's working perfectly next each other. Although I need to add an extra map to the page, like a main location. in this case the maps in the nested content (sub locations) don't appear. See attached print-screens.
<img width="1992" alt="Screenshot 2019-09-27 at 21 19 10" src="https://user-images.githubusercontent.com/357974/65799899-174b3380-e16d-11e9-9eec-8c3927bbd799.png">
<img width="1994" alt="Screenshot 2019-09-27 at 21 19 40" src="https://user-images.githubusercontent.com/357974/65799900-174b3380-e16d-11e9-8da7-ce43a0a6ad21.png">

Any advice?
Thanks!

**Comment by ronaldbarendse** [comment]
I think the problem occurs because the Nested Content property isn't visible (so the map doesn't have a width/height) or the `mapsInitialized` callback is only fired once:
https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/41786ebeea5b1201a4980e9d5d4fb1d833232eb7/src/Our.Umbraco.GMaps/App_Plugins/Our.Umbraco.GMaps/js/our.umbraco.gmaps.controller.js#L393

**Comment by levipadre** [comment]
I don’t know, maybe it’s related. But when I remove the main map, the nested maps start to work.

**Comment by richarth** [comment]
I had the same issue when I had a property with a map and a macro in the grid that used a map.  When I removed the property I was no longer getting the error from the Google Maps JS that loading the maps JS twice would cause issues and the map loaded.

**Comment by ronaldbarendse** [comment]
@richarth Did those properties by any chance have different data types with different API keys? It checks whether the Google Maps Javascript API is loaded by looking whether the dynamically inserted script already exists using:

https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/41786ebeea5b1201a4980e9d5d4fb1d833232eb7/src/Our.Umbraco.GMaps/App_Plugins/Our.Umbraco.GMaps/js/our.umbraco.gmaps.factory.js#L11-L13

This may result in loading the library twice if different API keys (thus different URLs) are used, so maybe we should also check whether the library is already loaded using `if (window.google && window.google.maps) {}`. This won't prevent simultaneous loading though (it still inserts the second script with another key while the first is still loading and `google.maps` isn't available yet).

**Comment by richarth** [comment]
When editing the page, the map appears fine on a property of my doc type which uses the Google Maps Single Marker data type.  The problem occurs with a grid data type property on the same doc type.

I have a map macro which has Google Maps Single Marker for the parameter.  When I try and insert the map macro into my grid data type, the panel slides in from the right to allow me to complete the macro parameters.  In the right hand panel that slides in, there is a blank space where the map should be and an error in the console that the Google Maps JavaScript API has been loaded multiple times.

Both data types are using the same API key and so the same URL.

**Comment by tomvanenckevort** [comment]
I think the main problem of this issue is the fact that the autocomplete and map canvas DOM elements are using an ID. When multiple editors are added to the same page (either via Nested Content elements, or just multiple properties on the same doc type) the JS will only run against the first DOM element with those IDs.

I've now submitted a PR that removes the ID attributes and replaces them with CSS class selectors. It also will go an find those elements within the element scope of the property editor, rather than the whole document as it was doing before.

That will then allow multiple maps to be used on the same node.

**Comment by ronaldbarendse** [comment]
@tomvanenckevort That indeed makes a lot of sense! The editor works without problems in repeating Nested Content items, because only a single map is shown/active at a time, but having it on a page property _and_ NC item means both are active 👍
