### ISSUE TITLE
Request to move location of API Key

### ISSUE THREAD

**Issue by NikRimington** [ArnoldV/Our.Umbraco.GMaps#18]
It's frustrating having an API key configured explicitly on a data type. Would it be possible to move the API key to an AppSetting so it can be varied easily for different environments. At the minute, it's impossible to use different keys on different environments without the risk of overriding the key accidentally. 

Example: Dev environments use internal key, and Live/UAT use the clients API key so they are responsible for billing.

**Comment by ronaldbarendse** [comment]
Getting the API key from a generic setting is indeed a very good idea! You also give very valid examples, it even makes me consider removing the key from the data type configuration entirely.

We could just add a fallback (in case the key isn't specified on the data type) for now. That would only require some logic in retrieving and storing the key:
- Retrieve: if the data type API key is empty, get if from the `Our.Umbraco.GMaps.ApiKey` application setting;
- Store: if the API key is the same as the application setting, do not save it on the data type.

A better solution would be to make it pluggable, so can write your own provider to get the right key (e.g. based on data type or hostname, from environment variables, files, etc.).

**Comment by ArnoldV** [comment]
Yes it makes a lot of sense to also have it on other locations. 
The original idea to have this on the datatype is so that everyone can setup google maps. No access to all code (like web.config) needed. So we can make it pluggable or a an advanced config that depends on hostname. Would love to keep the original idea in mind :)

**Comment by ronaldbarendse** [comment]
On another note: the API key is currently saved in the value on the content property, so changing the key in the data type configuration doesn't change the stored value. This requires loading the GMaps editor and save/publish the page to update the API key (if the front-end uses `MapConfig.ApiKey`).

This can be fixed by ignoring that property when storing the JSON value and restoring the current API key in the Property Value Converter (like the Grid editor does with it's settings and Image Cropper with crops).

**Comment by ronaldbarendse** [comment]
> This can be fixed by ignoring that property when storing the JSON value and restoring the current API key in the Property Value Converter (like the Grid editor does with it's settings and Image Cropper with crops).

This is now fixed in version 1.3.3 🎉 The API key is still stored in the data type configuration though, so I'll leave this issue open for now...

**Comment by bjarnef** [comment]
Something to consider is than in a multi-site setup, the client might want to use a different API key for each of the sites. Although most sites probably are separated in individual Umbraco projects, in some cases it makes sense to place multiple sites in same Umbraco project when the overall layout is similar and each site is its own brand.

Also on Umbraco Cloud with a baseline project, the baseline project will contain all sites.

To be able to each different API keys it would require a datatype instance per site and probably a document type for each site using the relevant datatype instance.
