### ISSUE TITLE
Style is null throwing an exception

### ISSUE THREAD

**Issue by Jogai** [ArnoldV/Our.Umbraco.GMaps#24]
I filled the custom mapstyle option in the data type, but its not available in the view on the frontend. Maybe related to https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/10, but if I read that correct the style setting is only for the fallback address? That shouldnt be the case since the partial view throws a null reference exception.

**Comment by ronaldbarendse** [comment]
This is probably the same issue as with the API key (see https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/18#issuecomment-647467187): the map style is stored in the property value, so changing the editor configuration doesn't change that value.

Currently, you need to open the content/editor and save/publish to update the map style that's stored in the property value.

This can be fixed by not storing the map style in the property value and automatically set it from the configuration in the PVC. The null-checks still need to be done though, as you should ensure your code even works without a map style set...

**Comment by Jogai** [comment]
Ok that clears it up. But yeah, the null-checks should be there if its this easy to get it wrong.
