### ISSUE TITLE
City field is often empty

### ISSUE THREAD

**Issue by HelgeNorvang** [ArnoldV/Our.Umbraco.GMaps#41]
Umbraco v8.10.1
Our.Umbraco.Gmaps v1.3.3

Searching for an address in Gmaps gives a full and correct address while typing and it seems to be working. But in most cases, the City field is empty after Saving/Publishing in backoffice. Not null, but an empty string.
This happens about 9 out of 10 times.

![image](https://user-images.githubusercontent.com/10958353/109858242-db6aa680-7c5b-11eb-8651-e31b13333914.png)

**Comment by ronaldbarendse** [comment]
Looks like the returned data from the Place API is slightly different on some results and the following method can't correctly parse the city:
https://github.com/ArnoldV/Our.Umbraco.GMaps/blob/68108307f81a1377231f5a0d7f9ea0d49ab2df22/Our.Umbraco.GMaps/App_Plugins/Our.Umbraco.GMaps/js/our.umbraco.gmaps.controller.js#L135

If you can provide more information on which result fields contains the correct city value besides the existing `locality` and `sublocality` (and 5 additional levels), we could update the parsing logic. The default values are set to empty strings, so that's expected behavior.
