### ISSUE TITLE
Umbraco 9 version?

### ISSUE THREAD

**Issue by shearer3000** [ArnoldV/Our.Umbraco.GMaps#45]
hello - are you considering a version for Umbraco 9 by any chance? thanks

**Comment by philipdanielhayton** [comment]
Any news on this now that v9 has released?

**Comment by ArnoldV** [comment]
When @ronaldbarendse and I find some time we will create it. The 'funny' things is that since this package was build both Ronald and I got hired by Umbraco HQ now and are busier than ever with Umbraco, but not on end-customer projects we could implement this for 🙈

It should actually not be that complex, since all angular things can stay the same. We got somet thoughs for a v2 version, but it might make most sense to just have this available with same data model so you can at least migrate to v9 easily.

**Comment by philipdanielhayton** [comment]
Ha, wow congrats on getting hired by HQ 👏🏻

Yeah I think it would be great if everything was the same and it was just re-packed to be compatible with v9 the ecosystem.

**Comment by cheeseytoastie** [comment]
I got this working but I was in a bit of mess with the branches. Seems develop is a bit borked? 

I'm not really sure how to create a PR for a package (as I'm not sure how you commit without checking in a website project too and with the change to v9 I don't feel confident I'd get this working). But it is a simple lift and shift and works nicely,.

If anyone is in a bind I'd be happy to supply a dll until this is done in nuget.
