### ISSUE TITLE
Auto-complete feature doesn't work when that is nested in a component

### ISSUE THREAD

**Issue by paria1420** [ArnoldV/Our.Umbraco.GMaps#47]
I have tried to use Gmaps property editor in a component, but autocomplete doesn't show anything when you start to type in the search input. I can drag and select a place but it is not really comfortable searching and tagging a place.
I am not sure but it seems the event listener has a problem.

**Comment by ronaldbarendse** [comment]
Can you clarify what you mean by 'in a component'? And can you confirm the API key also has the Geocoding and Place API enabled?

**Comment by paria1420** [comment]
yes, the API is working correctly.
I have a component the document type is like this:
![image](https://user-images.githubusercontent.com/49955996/139691280-3d4426f5-d22d-4b57-8c58-b33117899bbc.png)
when I try to add content to it the auto complete doesn't work:
![image](https://user-images.githubusercontent.com/49955996/139691540-1baa57aa-58e0-4cab-9a70-da7d83d89ba9.png)
but I am able to darg map manually and set a place but it's not very useful.

**Comment by ronaldbarendse** [comment]
@paria1420 The auto-complete field indeed wasn't working correctly in overlays, which is used by the Block List editor (when not using inline mode). This is already reported in https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/22 and https://github.com/ArnoldV/Our.Umbraco.GMaps/issues/40, which is fixed in https://github.com/ArnoldV/Our.Umbraco.GMaps/pull/23. Please make sure to upgrade to the latest version.
